title: 小白工作室
description: 欢迎光临
show_downloads: false
google_analytics: UA-153523414-1
theme: jekyll-theme-cayman
lang: zh-CN
permalink: none
date_format: '%-m月%-d日，%Y年'

github:
  url: https://github.com/heyxiaobai

gitalk:
  clientID: e5ca1276c1f62b914904
  clientSecret: 2da53bd6578a7fede484ba40cf6bc02bcc80f758
  repo: xiaobaistudio.github.io
  owner: xiaobaistudio
  admin: heyxiaobai